version: 2.1

orbs:
  python: circleci/python@1.2.0
  docker: circleci/docker@2.1.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8.11
    steps:
      - checkout
      - run:
          name: Set up Python Environment
          command: |
            python -m venv venv
            source venv/bin/activate
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Unit Tests with Coverage
          command: pytest --cov --cov-report=html

  build_and_push_docker:
    docker:
      - image: cimg/python:3.8.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t simple-server:0.1 .
      - run:
          name: Push to Docker Registry
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push simple-server:0.1

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
      - build_and_push_docker:
          requires:
            - build_and_test
