apiVersion: v1
kind: Service
metadata:
  name: simple-server
spec:
  type: NodePort
  selector:
    app: simple-server
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 8081
      targetPort: 8081
      # Campo opcional
      # Por defecto y por comodidad, el plano de control de Kubernetes asignará el puerto desde un rango (por defecto: 30000-32767)
      nodePort: 30007